version: '3.8'

services:
  flaskapp:
    build: .
    restart: always
    environment:
      - FLASK_ENV=development  # Recomendado para entornos fuera de desarrollo
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://bookstore_user:bookstore_pass@bookstore-db.cr6oemqg45kn.us-east-1.rds.amazonaws.com:3306/bookstore
    ports:
      - "5000:5000"
    volumes:
      - /mnt/efs/bookstore/static:/app/static
    # Elimina la dependencia del servicio "db"
    networks:
      - bookstore_net

# Elimina el servicio "db" y el volumen "db_data"
networks:
  bookstore_net:
